### ISSUE TITLE
DigitalPulse has parameters switched backwards

### ISSUE THREAD

**Issue by georgeHayRiv** [luisllamasbinaburo/Arduino-AsyncStepper#1]
`void AsyncStepper::DigitalPulse(int pin)
{
	digitalWrite(HIGH, pin);
	digitalWrite(LOW, pin);
}
`
Should be
`void AsyncStepper::DigitalPulse(int pin)
{
	digitalWrite(pin, HIGH);
	digitalWrite(pin, LOW);
}`
I am dealing with a stepper driver board that has a pin for direction and a pin to trigger a step. Even with the above fixed it will not make the motor run. I did extract some of your code and have it working. For this stepper board the direction is set once at the start and each run through Update() does a DigitalPulse() on the step pin.

**Comment by luisllamasbinaburo** [comment]
Open a PR and make you proposal on it. Thanks!
